django/learn-basics/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls'))

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

django/learn-basics/myproject/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name='list'),
    path('new-post/', views.new_post, name='new-post'),
    path('<slug:slug>', views.post_page, name='post_page'),
]

django/learn-basics/myproject/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.users_home, name='users_home'),
    path('register/', views.register, name='register'),
    path("login/", views.login_view, name="login"),
    path('logout/', views.logout_view, name='logout')
]

django/learn-basics/myproject/posts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    
    def __str__(self):
        return self.title
    
 

django/learn-basics/myproject/users/models.py
from django.db import models

# Create your models here.

django/learn-basics/myproject/posts/forms.py
from  django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ["title", "body", "slug", "banner"]
        

django/learn-basics/myproject/myproject/views.py
# from django.http import HttpResponse
from django.shortcuts import render


def homepage(request):
    return render(request, 'home.html')
    # return HttpResponse("Hello World!")


def about(request):
    return render(request, 'about.html')
    # return HttpResponse("About page")

django/learn-basics/myproject/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.

def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', {'posts' : posts} )

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html',{'post': post})

@login_required(login_url="/users/login/")  # checks if user is logged in, if not, redirect. 
def new_post(request):
    if request.method == "POST":
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return redirect("posts:list")
    else:
        form = forms.CreatePost()
        return render(request, 'posts/new-post.html', {"form": form})

    

django/learn-basics/myproject/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.

def users_home(request):
    return HttpResponse("Users list goes here..")


def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            #form.save()
            login(request, form.save())
            return redirect("posts:list")
    else:
        form = UserCreationForm()
        
    return render(request, 'users/register.html', {"form" : form})


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
           login(request, form.get_user())
           if "next" in request.POST:
               return redirect(request.POST.get("next"))
           else:
               return redirect("posts:list")
        
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {"form": form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("posts:list")
    

django/learn-basics/myproject/posts/templates/posts/new-post.html
{% extends "layout.html" %}

{% block title %}
    <h1>new post page</h1>
{% endblock title %}

{% block content %}
    <section>
        <h1>new post</h1>
        <form  class ="form-with-class" action=" {% url 'posts:new-post' %} " method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit">Add Post</button>
        </form>
    </section>
{% endblock content %}

django/learn-basics/myproject/posts/templates/posts/post_page.html
{% extends "layout.html" %}

{% block title %}
    {{post.title}}
{% endblock title %}

{% block content %}
    <section>
        <img
        class="banner"
        src="{{ post.banner.url }}" 
        alt="{{ post.title }}"
    />
        <h1>{{post.title}}</h1>
        <p> {{post.date}} </p>
        <p> {{post.body}} </p>
    </section>
{% endblock content %}

django/learn-basics/myproject/posts/templates/posts/posts_list.html
{% extends "layout.html" %}

{% block title %}
    Posts
{% endblock title %}

{% block content %}
    <section>
        <h1>Posts</h1>
        {% for post in posts  %}
            <article class="post">
                <h2> 
                    <a href="{% url 'posts:post_page' slug=post.slug %}">
                        {{post.title}}
                    </a>
                </h2>
                <p> {{post.date}} </p>
                <p> {{post.body}} by {{ post.author }} </p>
            </article>
        {% endfor %}
    </section>
{% endblock content %}

django/learn-basics/myproject/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <h1> Check out my <a href="/">Home</a> page! </h1>
</body>
</html>

django/learn-basics/myproject/templates/home.html
{% extends "layout.html" %}

{% block title %}
    Home
{% endblock title %}
    
{% block content %}
    <h1>Home</h1>
    <p>Check out my <a href="/about">About </a> page too! </p>
{% endblock content %}

django/learn-basics/myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
    <title>
    {% block title %}
        Django App
    {% endblock title %}
    </title>
</head>
<body>
    <nav>
        <a href="/" title="Home" > 🏠</a> |
        <a href="/about" title="About"> 😀</a> |
        <a href="{% url 'posts:list' %}" title="Posts">📰</a>|
        {% if user.is_authenticated %}
            <a href="{% url 'posts:new-post' %}" title="New Post">🆕</a>|
            <form class="logout" method="POST" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button class="logout-button" aria-label="Logout" title="Logout"> 
                    👋🏿
                </button>
            </form>
        {% else %}
            <a href="{% url 'users:register' %}" title="Register">🚀</a>|
            <a href="{% url 'users:login' %}" title="Login">🔒</a>|
        {% endif %}

    </nav>
    <main>
        {% block content %}
        
        {% endblock content %}
    </main>
</body>
</html>

django/learn-basics/myproject/users/templates/users/login.html
{% extends "layout.html" %}

{% block title %}
    Login
{% endblock title %}

{% block content %}
        <h1>Login here...</h1>

        <form class="form-with-validation" action="{% url 'users:login' %}" method="POST">
            {% csrf_token %}
            {{ form }}
            {% if request.GET.next %}
                <input type="hidden" name="next" value={{ request.GET.next }}> 
            {% endif %}
            <button class="form-submit">Submit</button>
        </form>

{% endblock content %}

django/learn-basics/myproject/users/templates/users/register.html
{% extends "layout.html" %}

{% block title %}
    Register
{% endblock title %}

{% block content %}
        <h1>Register here...</h1>

        <form class="form-with-validation" action="/users/register/" method="POST">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit">Submit</button>
        </form>

{% endblock content %}